---
title: "Variational Approximations"
author: "Ricardo Cortez and Ben Graf"
date: "4/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

- do we want to include the other examples in the paper??
  -- I say no 


# Introduction
  (feedback from presentation)
  - what's the problem? 
  - what are we approximating?

# Density Transform Approach

In general variational approximations derive a lower bound, and then iteratively approximate the parameters of a conditional function with guidance from measuring the distance between the approximations and the lower bound. The Density Transform Approach attempts to approximate the posterior densities, in a Bayesian context, by other densities in which a more tractable is found. There are two main approaches in selecting the approximating density the first is *Product Density Transform* and the second is *Parametric Density Transform*. Both of these transforms are guided by the Kullback-Leibler Divergence (Distance). 

## Kullback-Leibler Divergence

## Product Density Transforms

### Connection with Gibbs Sampling

### Product Data Transfer Example 1: Normal Random Sample

### Product Data Transfer Example 2: Linear Mixed Model

# Parametric Density Transform

### Parametric Density Transform Example: Poisson Regression

# Tangent Transform Approach 

## Tangent Transform Approach Example: Bayesian Logistic Regression

# A Note on Frequentist Inference

# Conclusion

